# Generated by Django 6.0.6 on 2026-07-10 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room_created_at_room_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
