# Generated by Django 6.0.6 on 2026-07-11 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelimage_options_hotelimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelpolicy',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='hotelpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
