# Generated by Django 6.0.6 on 2026-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('net_banking', 'Net Banking'), ('wallet', 'Wallet'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
