# Generated by Django 6.0.6 on 2026-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flightbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(default='FB-TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
