# Generated by Django 6.0.6 on 2026-07-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flightbooking_booking_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightbooking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='booking_reference',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='status',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
